package com.typewritermc.engine.paper.entry.entries

import com.typewritermc.core.entries.Query
import com.typewritermc.core.extension.annotations.Generated
import com.typewritermc.core.extension.annotations.Help
import com.typewritermc.core.extension.annotations.Tags
import com.typewritermc.core.utils.failure
import com.typewritermc.engine.paper.entry.AssetManager
import com.typewritermc.engine.paper.entry.StaticEntry
import org.koin.java.KoinJavaComponent

@Tags("asset")
interface AssetEntry : StaticEntry {
    @Help("资源的路径。")
    val path: String
}

suspend fun AssetEntry.hasData(): Boolean {
    return KoinJavaComponent.get<AssetManager>(AssetManager::class.java).containsAsset(this)
}

suspend fun AssetEntry.data(): String? {
    return KoinJavaComponent.get<AssetManager>(AssetManager::class.java).fetchAsset(this)
}

suspend fun AssetEntry.data(data: String) {
    KoinJavaComponent.get<AssetManager>(AssetManager::class.java).storeAsset(this, data)
}

/**
 * Artifacts are assets that are generated by the plugin itself.
 */
@Tags("artifact")
interface ArtifactEntry : AssetEntry {
    @Help("这是工件的唯一标识符。不应更改！")
    @Generated
    val artifactId: String

    val extension: String
        get() = "json"

    override val path: String
        get() = "artifacts/${artifactId}.${extension}"
}

fun getAssetFromFieldValue(fieldValue: Any?): Result<AssetEntry> {
    if (fieldValue !is String) {
        return failure("字段值必须是一个字符串！")
    }

    if (fieldValue.isBlank()) {
        return failure("必须选择一个资源。")
    }

    val artifact = Query.findById<AssetEntry>(fieldValue)
        ?: return failure("找不到 ID 为 $fieldValue 的工件")

    return Result.success(artifact)
}