package me.gabber235.typewriter.entry.entries

import me.gabber235.typewriter.adapters.Tags
import me.gabber235.typewriter.adapters.modifiers.Generated
import me.gabber235.typewriter.adapters.modifiers.Help
import me.gabber235.typewriter.entry.Query
import me.gabber235.typewriter.entry.StaticEntry
import me.gabber235.typewriter.utils.failure

@Tags("asset")
interface AssetEntry : StaticEntry {
    @Help("资源的路径。")
    val path: String
}

/**
 * Artifacts are assets that are generated by the plugin itself.
 */
@Tags("artifact")
interface ArtifactEntry : AssetEntry {
    @Help("这是工件的唯一标识符。不应更改！")
    @Generated
    val artifactId: String

    val extension: String
        get() = "json"

    override val path: String
        get() = "artifacts/${artifactId}.${extension}"
}

fun getAssetFromFieldValue(fieldValue: Any?): Result<AssetEntry> {
    if (fieldValue !is String) {
        return failure("字段值必须是一个字符串！")
    }

    if (fieldValue.isBlank()) {
        return failure("必须选择一个资源。")
    }

    val artifact = Query.findById<AssetEntry>(fieldValue)
        ?: return failure("找不到 ID 为 $fieldValue 的工件")

    return Result.success(artifact)
}