name: Build Typewriter Plugin

on: [workflow_call,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build Plugin
        uses: ./.github/actions/build-plugin
      - name: Upload Plugin
        uses: actions/upload-artifact@v4
        with:
          name: typewriter.jar
          path: plugin/build/libs/typewriter.jar
